# Prefix: Ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# WASD pane naviagation
bind -r w select-pane -U
bind -r a select-pane -L
bind -r s select-pane -D
bind -r d select-pane -R

# detach on v
bind v detach-client

# Resizer Panes
bind -r W resize-pane -U 5
bind -r A resize-pane -L 5
bind -r S resize-pane -D 5
bind -r D resize-pane -R 5

# Shortcurts
bind Tab last-window
bind Right split-window -h
bind Down split-window -v
bind Up kill-pane
bind t choose-tree -Zs
bind e choose-window
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
bind Space setw synchronize-panes \; display-message "sync #{?pane_synced,on,off}"

# Copy Mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel

#times
set -sg escape-time 0
set -g repeat-time 300
